In [ ]:
!pip3 install torch
!pip3 install torchvision

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
#구글드라이브를 마운트한다

Mounted at /content/drive


In [ ]:
import torch as tc
import numpy as np

In [ ]:
#파이썬의 list 와 float 타입의 텐서를 통한 초기화
arr = [1,2]
mytensor = tc.tensor(arr)
val = 2.0
mytensor2 = tc.tensor(val)
print(mytensor)
print(mytensor2)

tensor([1, 2])
tensor(2.)


In [ ]:
nparr = np.array([1,2])
x_t = tc.from_numpy(nparr)
print(nparr)
print(x_t)

[1 2]
tensor([1, 2])


In [ ]:
zerotensor = tc.zeros((2,3)) #2 by 3 텐서를 0으로 초기화
onetensor = tc.ones((2,3)) #2 by 3 텐서를 1로 초기화
randtensor = tc.randn((2,3)) #2 by 3 텐서를 난수로 초기화,randn 에서 초기화된 각 element인 x는 -1<= x <=1 임
print(zerotensor)
print(onetensor)
print(randtensor)
zerotensor.shape #tensor 의 사이즈를 반환

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[-0.4315,  1.7914, -0.1661],
        [-0.2288,  0.1864,  0.5186]])


torch.Size([2, 3])

In [ ]:
t_val = tc.tensor(val)
t_val.dtype #tensor 의 데이터 타입을 반환 (float32) 여기서 float 32 는 4바이트(32비트)로 표현되는 부동소수점 숫자를 의미함

torch.float32

In [ ]:
arr2 = [1,2]
mytensor3 = tc.tensor(arr2)
print(mytensor3.dtype)
mytensor4 = tc.tensor(arr2,dtype=tc.float32) #텐서 초기화시 데이터타입을 설정할 수 있다
print(mytensor4.dtype)

torch.int64
torch.float32


In [ ]:
print(mytensor3.device)
'''텐서가 할당된 장치를 알 수 있다 (cpu) 기본적으로 텐서는 cpu 에 할당된다
런타임 유형 변경을 통해 GPU가 활성화된 상태라면 CUDA가 설치되어 있으므로 torch.cuda.is_available()로 CUDA 사용 가능 여부를 확인하고 사용할 수 있다.
GPU가 사용 가능하다면, torch.device('cuda')로 장치 객체를 생성한 뒤, 텐서를 GPU에 할당할 수 있다.'''
if tc.cuda.is_available():
  mydevice = tc.device('cuda') #cuda 장치 객체 생성
  mytensor5 = tc.tensor(arr2,device=mydevice) #tensor 생성시 device를 cuda 로 설정
  print(mytensor5.device)

cpu
cuda:0


In [ ]:
#텐서의 기본연산
c = 10
print(c*mytensor3) #스칼라곱

print(onetensor + randtensor)#텐서의 덧셈


tensor([10, 20])
tensor([[0.5685, 2.7914, 0.8339],
        [0.7712, 1.1864, 1.5186]])


In [ ]:
brdtensor = tc.tensor([1,2,3])
brdtensor2 = tc.tensor([[1,2,3],[3,4,5]])
print(brdtensor*brdtensor2)
''' 브로드 캐스팅으로 brdtensor 의 shape 은 (3,) 이지만 brdtensor2 와의 연산을 위해 shape이 (2,3) 이므로 전환된다
이때 1행의 원소 [1,2,3]을 그대로 가지고 오므로 brdtensor 는 [[1,2,3],[1,2,3]] 이 된다
추가로 텐서의 연산규칙은 행렬곱의 연산방식(Matrix Multiplication)인 앞 행렬의 행벡터와 뒷행렬의 열벡터를 내적하는것이 아닌 원소별 곱셈(element-wise Multiplication)이다
즉 결과텐서의 1행인 [3,8,15]는 [1*3, 2*4, 3*5] 이다.'''
#그 외 알면 용이한 메서드 몇 개
brdtensor3 = tc.arange(9)
#arange 함수는 파이썬의 range 와 같음
print(brdtensor3.reshape(3,3))
#reshape 함수는 3by3dmfh 텐서를 재배열 해준다


tensor([[ 1,  4,  9],
        [ 3,  8, 15]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [ ]:
#행렬곱을 해주는 함수 matmul
# tc.matmul(텐서1,텐서2) 혹은 텐서1@텐서2 와 같은식으로 적는다
print(tc.matmul(newtensor,newtensor2))
print(newtensor@newtensor2)
#둘의 연산 결과가 같음을 알 수 있다.

tensor([[ 0.9020, -1.2905,  1.4520],
        [-0.5196,  0.4843, -2.7218],
        [-0.0078,  0.5390,  3.8282]])
tensor([[ 0.9020, -1.2905,  1.4520],
        [-0.5196,  0.4843, -2.7218],
        [-0.0078,  0.5390,  3.8282]])


In [ ]:
#색인을 통한 접근
# 색인화 : 텐서의 특정 element 에 접근을 용이하게 한다 보통 텐서는 행렬의 배열이므로 i,j,k 혹은 그 이상의 색인이 필요하다 (3차원 이상)
newtensor3 = tc.tensor([[[3,7,9],[2,4,5]],[[8,6,2],[3,9,1]]])
#여기서 텐서는 [행렬0,행렬1] 의 형태이고 행렬0 = [[3,7,9],[2,4,5]] 의 2by3 행렬이고  행렬1 = [[8,6,2],[3,9,1]] 이다
#여기서 색인 i,j,k = 0,1,1 이라고 하면 i는 행렬 0을 가르키고 j와 k 는 행렬 0의 (1,1) element 를 가르킨다 즉 4를 가르킨다
i,j,k = 0,1,1
print(newtensor3[i,j,k])
# : 는 해당 차원의 데이터 부분 집합 전체를 가져오는 역할임 즉 행렬0의 모든 행 모든 열을 반환함 즉 0~끝까지를 의미함
# 시작 : 끝 의 형태로 쓴다
print(newtensor3[0,:,:])
print(newtensor3[0])
# 색인으로 0,j:,: 를 쓰면 1행 이상의 모든 원소를 반환한다
print(newtensor3[0,j:,:])
# 또 0, :j , : 를 쓰면 1행 까지의 즉 1미만의 모든 원소를 반환한다
print(newtensor3[0,:j,:])
#특정 원소를 수정하는것도 가능함 (5를 1로 수정)
newtensor3[0,1,2] = 1
print(newtensor3)
#또 행렬의 부분행렬을 새로운 행렬로 대체 가능함
subtensor = tc.randn((2,3))
newtensor3[0,:,:] = subtensor
print(newtensor3)
#여기서 반환값이 -1에서 1사이 난수가 아닌 -1,0,1,로 나오는것은 dtype 이 float 이 아닌 정수형이기 때문임 따라서 dtype 을 float 으로 바꿔주면
newtensor4 = tc.tensor([[[3,7,9],[2,4,5]],[[8,6,2],[3,9,1]]],dtype = float)
newtensor4[0,:,:] = subtensor
print(newtensor4)


tensor(4)
tensor([[3, 7, 9],
        [2, 4, 5]])
tensor([[3, 7, 9],
        [2, 4, 5]])
tensor([[2, 4, 5]])
tensor([[3, 7, 9]])
tensor([[[3, 7, 9],
         [2, 4, 1]],

        [[8, 6, 2],
         [3, 9, 1]]])
tensor([[[ 1,  1,  0],
         [ 0,  0, -1]],

        [[ 8,  6,  2],
         [ 3,  9,  1]]])
tensor([[[ 1.4866,  1.1927,  0.8449],
         [ 0.1810, -0.5032, -1.7508]],

        [[ 8.0000,  6.0000,  2.0000],
         [ 3.0000,  9.0000,  1.0000]]], dtype=torch.float64)


# 자동미분
파이토치의 자동미분 라이브러리를 이용하면 함수의 도함수(혹은 편도함수)를 직접 구하지 않고 구할 수 있다. 그 대신 주어진 "지점"(입력값인 벡터)에서의 미분계수(혹은 편미분계수) 값을 구한다. 즉, 자동미분 라이브러리는 지정해준 점에서의 함수의 "순간 기울기"를 구하는 기능만을 갖고 있다. 이를 이용하면 미분가능한 모든 함수의 각 지점에서의 기울기를 구할 수 있다.

# 텐서 객체의 '.backward()' 메서드
파이토치에서 자동미분을 호출하는 메서드는 Tensor.backward()이다. "다른 텐서로부터 계산한 텐서 F"에 대해 F.backward()를 호출하면 파이토치는 F가 의존하는 모든 텐서에 대해 F의 편미분계수를 계산하도록 지시한다. 이 편미분계수들은 각각의 텐서들의 .grad 속성에 Tensor로 저장된다. 이때

requires_grad=True 를 통해 매개변수 requires_grad 값을 True 로 함으로써 자동 미분 추적을 허용하도록 설정해야한다.

backward() 호출: Tensor.backward()를 호출하면 해당 텐서로부터 계산된 모든 텐서에 대해 그래디언트(기울기)를 계산합니다. backward()는 스칼라 값에 대해서만 호출할 수 있습니다. 만약 텐서가 스칼라가 아니라면, 적절한 축소 연산을 통해 스칼라로 변환한 후 backward()를 호출해야 한다 (예: sum()).

예를 들어 아래와 같이 x, y, z 텐서가 있고, x,y,z의 함수로 정의된 f 텐서가 있는 상황에서의 편미분을 살펴보자.

In [ ]:
#파이토치를 활용한 자동미
x = tc.tensor(2.0, requires_grad = True) #상수텐서 x,y,z 생성
y = tc.tensor(3.0, requires_grad = True)
z = tc.tensor(1.5, requires_grad = True)

f = x**2 + y**2 + z**2
f.backward()
x.grad, y.grad, z.grad #각각 x,y,z 에 대한 편미분 계수이다


(tensor(4.), tensor(6.), tensor(3.))

f.backward()를 호출하게 되면 파이토치가 f의 각 변수에 대한 모든 편미분계수를 계산하도록 지시한다. 이는 역전파(backpropagation)과정에서의 연쇄법칙(chain rule)에 기반한 알고리즘을 사용하여 수행된다.

편미분 계수 반환
x, y, z의 .grad() 속성을 살펴보면  $\frac{\partial f}{\partial x}$,  $\frac{\partial f}{\partial y}$, $\frac{\partial f}{\partial z} $ 의 값을 얻을 수 있다. .grad()는 텐서로 구해진다.

# 파이토치 nn 모듈
파이토치의 nn 모듈은 신경망(Neural Networks)을 구성하는 계층(layer), 손실 함수(loss function), 활성화 함수(activation function) 등을 사용할 수 있도록 패키징한 모듈이다. 즉, nn 모듈은 신경망을 학습시키기 위한 다양한 구성 요소들을 제공하는 API이다.

In [ ]:
import torch.nn as nn

In [ ]:
input_dimention,output_dimention = 256,10
vector = tc.randn(256)
layer = nn.Linear(input_dimention, output_dimention, bias = True) #입력과 출력의 차원 결정 256, 10
output_vector = layer(vector)
print(output_vector)

tensor([ 1.1567, -1.0292,  0.5297,  0.6268, -0.2615, -0.7089,  0.2831, -0.0136,
         0.1801, -1.3455], grad_fn=<ViewBackward0>)


vector = tc.randn(256)을 통해서 -1 에서 1 사이의 평균이 0 이고 표준편차가 1이 되는 256개의 난수들을 원소로 하는 열벡터 생성하고 이를 입력값으로 사용한다
nn.Linear 을 통해서 입력받는 벡터의 차원과 출력하는 벡터의 차원을 결정한다 여기서 nn.Linear 은 선형변환이다.
내부적으로는 (10, 256) 크기의 가중치 행렬 W가 만들어진다.
즉, outputvector= W@vector+bias 이다.
여기서 W는 (output_dimension=10, input_dimension=256) 크기의 가중치 행렬이다.
또, b는 (output_dimension,) 크기의 편향 벡터. 즉, 길이가 10이고 1차원인, 편향 벡터이다.

아래코드는 위 과정이 내부적으로 이루어지는 것을 수동으로 1개 층에 대해서 표현한것이다.




In [ ]:
W = tc.rand(10,256)
b = tc.zeros(10,)
output = W@vector+b
print(output)

tensor([-16.5068,  -3.7954, -10.3025,  -9.3129, -11.6612,  -5.5093, -15.3803,
          4.4335,  -8.9609,  -8.8605])


이제 1차적으로 나온값들을 활성화 함수(은닉층 혹은 중간레이어에서 사용되는 함수로 ReLU 함수, Leaky ReLU함수, Sigmoid 함수 ,하이퍼볼릭 탄젠트 함수 등등)에 대입한 값을 layer2 의 입력값으로 받는다. 이와 같은 작업을 반복적으로 수행한 후 최종적으로는 SoftMax 함수(출력층에서 쓰이는 함수)를 통해 반환된 값을 사용한다.

2개층을 통해서 구현해보자. 또 ReLU 함수가 있을때와 없을때 반환값을 비교해보자.

In [ ]:
indim,featuredim,outdim = 784,256,10
vec = tc.randn(784)
layer1 = nn.Linear(indim,featuredim,bias=True)
layer2 = nn.Linear(featuredim,outdim,bias=True)
output = layer2(layer1(vec))
print(output)
relu = nn.ReLU()
newoutput = layer2(relu(layer1(vec)))
print(newoutput)


tensor([-0.0066,  0.9858,  0.4957,  0.5508, -0.0784, -0.7237, -0.3587, -0.3233,
        -0.2115, -0.5266], grad_fn=<ViewBackward0>)
tensor([-0.1012,  0.5412,  0.1775,  0.4222,  0.0132, -0.3693, -0.3719, -0.3362,
        -0.3097, -0.2944], grad_fn=<ViewBackward0>)


# nn.Module 클래스


In [ ]:
class BaseClassifier(nn.Module):
  def __init__(self,indim,featuredim,outdim):
    super(BaseClassifier,self).__init__()
    self.layer1 = nn.Linear(indim,featuredim,bias=True)
    self.layer2 = nn.Linear(featuredim,outdim,bias=True)
    self.relu = nn.ReLU()

  def forward(self,x):
    x = self.layer1(x)
    x = self.relu(x)
    out = self.layer2(x)
    return out

no_examples = 10
indim = 784
featuredim = 256
outdim = 10
x = tc.randn((no_examples,indim))
model = BaseClassifier(indim,featuredim,outdim)
output = model(x)

loss = nn.CrossEntropyLoss()
target = tc.tensor([0,3,2,8,2,9,3,7,1,6])
computedloss = loss(output,target)
computedloss.backward()

for p in model.parameters():
  print(p.shape)

from torch import optim
lr = 1e-3
optimizer = optim.SGD(model.parameters(),lr=lr)
optimizer.step()
optimizer.zero_grad()

torch.Size([256, 784])
torch.Size([256])
torch.Size([10, 256])
torch.Size([10])
